### ISSUE TITLE
Remove generated mesh files when running pre-processing test

### ISSUE THREAD

**Issue by keiyamamo** [KVSlab/Aneurysm_Workflow_FSI#57]
Running `test_pre_processing.py` creates quite many files and they are not automatically removed after the test is finished.
Could it be possible to improve the test so that newly generated files are removed after the test?

**Comment by johannesring** [comment]
Yes, I will fix this when I am back from vacation on Friday.

**Comment by keiyamamo** [comment]
Fixed #61
