### ISSUE TITLE
fsipy requires `morphMan` for all the functionality 

### ISSUE THREAD

**Issue by keiyamamo** [KVSlab/Aneurysm_Workflow_FSI#69]
https://github.com/KVSlab/Aneurysm_Workflow_FSI/blob/28422ae70158c4b6581ce0339308ae6ee25b6bcf/src/fsipy/__init__.py#L8-L10

I tried to use `fsipy-log-plotter` on the cluster and figured out that `morphMan` is required even when we just want to use post-processing tools. We could do same as `VaMPy` (use try: except method) but I do wonder if we even need this import in `__init__.py` under `src/`. It makes more sense to import functions but not really file itself. Hope to hear what you think! @johannesring @jorgensd

**Comment by johannesring** [comment]
@keiyamamo - Can you check if pull request #70 fixes the issue on the cluster?

**Comment by keiyamamo** [comment]
Hi @johannesring, 

Thanks for the fix! Yes, this fixes the issue. However, when I tried `fsipy-predeform-mesh`. I got the same error message due to `from . import automated_preprocessing` inside `src/fsipy/automatedPreprocessing/__init__.py`. Technically, you don’t need `morphMan` for using `fsipy-predeform-mesh`. Do you think it is possible to remove this error message or should we assume that the user has `morphMan` since `fsipy-predeform-mesh` is part of pre-processing?

**Comment by johannesring** [comment]
@keiyamamo - One way to solve this would be to create subfolders for the mesh generation (`automated_preprocessing.py`, `preprocessing_common.py` and `vmtkmeshgeneratorfsi.py`) and for the predeform script. Another way would be to move the predeform script to the post processing folder. What do you think?

**Comment by johannesring** [comment]
Fixed in PR #70.
