### ISSUE TITLE
SubMesh only works for single marker

### ISSUE THREAD

**Issue by keiyamamo** [KVSlab/Aneurysm_Workflow_FSI#85]
Hi @jorgensd 

I have a question specifically to you. In our framework, we separate the domain after simulation has completed using `SubMesh` function. So far, I’ve been using only single fluid/solid domain but we also use multiple fluids/solids. Base on the discussion [here](https://fenicsproject.org/qa/513/submesh-of-two-subdomains/), it seems not possible to define multiple domain using SubMesh with different markers (In the link, they enforce the different subdomains to have single marker?). 

So my question is : 
Is it possible to separate domains while keeping multiple markers for specific domain ? I also attached illustration where I try to explain what I want to achieve. Maybe is this something `MeshView` can handle?

https://github.com/KVSlab/Aneurysm_Workflow_FSI/blob/c6b8b5aa480417abe6ec4f9794ca354bc4b0830b/src/fsipy/automatedPostprocessing/postprocessing_mesh/separate_mesh.py#L39

![Screenshot 2023-10-23 at 16 04 49](https://github.com/KVSlab/Aneurysm_Workflow_FSI/assets/42674006/e02934f1-cf06-48a2-921d-2cb13b3dd93e)

**Comment by jorgensd** [comment]
Suggested solution from @keiyamamo  and I:
```python
from dolfin import *

mesh = UnitSquareMesh(20, 20)


class left(SubDomain):
    def inside(self, x, on_boundary):
        return x[0] < 0.2 and x[1] <= 0.5 + 1e3 * DOLFIN_EPS


class top(SubDomain):
    def inside(self, x, on_boundary):
        return x[0] < 0.2 and x[1] > 0.5 - 1e3 * DOLFIN_EPS


mf = MeshFunction("size_t", mesh, mesh.topology().dim(), 1)

left().mark(mf, 2)
top().mark(mf, 3)


merged_mf = MeshFunction("size_t", mesh, mesh.topology().dim(), 1)
tmp_array = merged_mf.array().copy()
tmp_array[mf.where_equal(2)] = 5
tmp_array[mf.where_equal(3)] = 5
merged_mf.set_values(tmp_array)

solid_mesh = SubMesh(mesh, merged_mf, 5)


mf_sub = MeshFunction("size_t", solid_mesh, solid_mesh.topology().dim(), 1)
parent_cell_indices = solid_mesh.data().array(
    "parent_cell_indices", solid_mesh.topology().dim())
tmp_sub_array = mf_sub.array().copy()
tmp_sub_array[:] = mf.array()[parent_cell_indices]
print(tmp_sub_array)
mf_sub.set_values(tmp_sub_array)

File("SubMesh_mf.pvd") << mf_sub

File("MF.pvd") << mf
```
producing
![image](https://github.com/KVSlab/Aneurysm_Workflow_FSI/assets/8554300/8b876017-c1a4-4a49-930b-27da7b27b2a4)
